/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangmanAssingmentPKG;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author keshinijayasinghe
 */
public class mainMenu extends javax.swing.JFrame {
    
    public static String level = "";
    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        setSize(1101, 700);
        setLocationRelativeTo(null);
        setResizable(false);
        //adding the bakcground image
        ImageIcon img = new ImageIcon("images/mainMenu.jpg");
        JLabel lblBack = new JLabel(img); //adding the image a jlabel
        setContentPane(lblBack); //adding the jlabel to theJPane
        initComponents();
       

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMedium = new javax.swing.JButton();
        btnDifficult = new javax.swing.JButton();
        btnEasy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMedium.setBackground(new java.awt.Color(239, 130, 13));
        btnMedium.setFont(new java.awt.Font("Harrington", 0, 36)); // NOI18N
        btnMedium.setForeground(new java.awt.Color(255, 255, 255));
        btnMedium.setText("MEDIUM");
        btnMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediumActionPerformed(evt);
            }
        });

        btnDifficult.setBackground(new java.awt.Color(239, 130, 13));
        btnDifficult.setFont(new java.awt.Font("Harrington", 0, 36)); // NOI18N
        btnDifficult.setForeground(new java.awt.Color(255, 255, 255));
        btnDifficult.setText("DIFFICULT");
        btnDifficult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDifficultActionPerformed(evt);
            }
        });

        btnEasy.setBackground(new java.awt.Color(239, 130, 13));
        btnEasy.setFont(new java.awt.Font("Harrington", 0, 36)); // NOI18N
        btnEasy.setForeground(new java.awt.Color(255, 255, 255));
        btnEasy.setText("EASY");
        btnEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEasyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(677, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEasy, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDifficult, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btnEasy, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnDifficult, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediumActionPerformed
      //creates a new hangman object with the level as a parameter to the contructor
        Hangman hm = new Hangman("medium");
        this.setVisible(false);
        hm.setVisible(true);
        
    }//GEN-LAST:event_btnMediumActionPerformed

    private void btnDifficultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDifficultActionPerformed
        //creates a new hangman object with the level as a parameter to the contructor
        Hangman hm = new Hangman("difficult");
        this.setVisible(false);
        hm.setVisible(true);
    }//GEN-LAST:event_btnDifficultActionPerformed

    private void btnEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEasyActionPerformed
        //creates a new hangman object with the level as a parameter to the contructor
        Hangman hm = new Hangman("easy");
        this.setVisible(false);
        hm.setVisible(true);
    }//GEN-LAST:event_btnEasyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDifficult;
    private javax.swing.JButton btnEasy;
    private javax.swing.JButton btnMedium;
    // End of variables declaration//GEN-END:variables
}
